version: '3.9'
services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    container_name: party-invite-app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  test:
    build:
      dockerfile: ./Dockerfile.test
      context: .
